name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build -p client --release
          cargo build -p server --release

      - name: Package
        shell: bash
        run: |
          # Créer un dossier temporaire par plateforme
          mkdir -p dist
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp target/release/client.exe dist/
            cp target/release/server.exe dist/
            7z a bombeat-windows.zip ./dist/*
          else
            cp target/release/client dist/
            cp target/release/server dist/
            zip -j bombeat-linux.zip ./dist/*
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bombeat-${{ matrix.os }}
          path: "*.zip"
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Bombeatbyx-windows.zip
            Bombeatbyx-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}